// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc3kgXjJIZF6zh8QXQZ2z_eNYpJnu0KVg',
    appId: '1:117582804845:web:503ed945d737b765f64c64',
    messagingSenderId: '117582804845',
    projectId: 'task07-real-estate-app-beg',
    authDomain: 'task07-real-estate-app-beg.firebaseapp.com',
    storageBucket: 'task07-real-estate-app-beg.firebasestorage.app',
    measurementId: 'G-R977TKPRZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZeEbJ9d-y6MmqOePVDPr8OUvV0-N1k7A',
    appId: '1:117582804845:android:67e5f980d5f9041af64c64',
    messagingSenderId: '117582804845',
    projectId: 'task07-real-estate-app-beg',
    storageBucket: 'task07-real-estate-app-beg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy4IXYPUAfwu8RS-Wr09jTYIGEe_maNRo',
    appId: '1:117582804845:ios:3ab662db581c4770f64c64',
    messagingSenderId: '117582804845',
    projectId: 'task07-real-estate-app-beg',
    storageBucket: 'task07-real-estate-app-beg.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask07RealEstateAppBeg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy4IXYPUAfwu8RS-Wr09jTYIGEe_maNRo',
    appId: '1:117582804845:ios:3ab662db581c4770f64c64',
    messagingSenderId: '117582804845',
    projectId: 'task07-real-estate-app-beg',
    storageBucket: 'task07-real-estate-app-beg.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask07RealEstateAppBeg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc3kgXjJIZF6zh8QXQZ2z_eNYpJnu0KVg',
    appId: '1:117582804845:web:d2ff11c062757e94f64c64',
    messagingSenderId: '117582804845',
    projectId: 'task07-real-estate-app-beg',
    authDomain: 'task07-real-estate-app-beg.firebaseapp.com',
    storageBucket: 'task07-real-estate-app-beg.firebasestorage.app',
    measurementId: 'G-3DJ5HKL35V',
  );
}
